name: lk-polymer
version: 0.0.1
dependencies:
#  polymer: ^1.0.0
  polymer:
    git: 
      url: https://github.com/dart-lang/polymer-dart.git
      ref: 1.0.0-rc.2
  web_components: ^0.12.0
  reflectable: ^0.3.0
  polymer_elements:
transformers:
- web_components:
    entry_points:
      - web/index.html
- reflectable:
    entry_points:
      - web/index.dart